// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIhuE1VohrKfJ2G477J_-zvhhg3BMxQ8',
    appId: '1:965296088139:web:35ca84a36d645f2489d9ce',
    messagingSenderId: '965296088139',
    projectId: 'morty-pos',
    authDomain: 'morty-pos.firebaseapp.com',
    storageBucket: 'morty-pos.appspot.com',
    measurementId: 'G-P3E82YYE7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtxrFeAoek7jyNmUDKYdo1Ryv8LoUshY',
    appId: '1:965296088139:android:0657ba66aa4dfb1e89d9ce',
    messagingSenderId: '965296088139',
    projectId: 'morty-pos',
    storageBucket: 'morty-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy9zTaaWLKwBVWgGOIOo0RLPozS4kQbyI',
    appId: '1:965296088139:ios:1b4c355640bbe20389d9ce',
    messagingSenderId: '965296088139',
    projectId: 'morty-pos',
    storageBucket: 'morty-pos.appspot.com',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy9zTaaWLKwBVWgGOIOo0RLPozS4kQbyI',
    appId: '1:965296088139:ios:1b4c355640bbe20389d9ce',
    messagingSenderId: '965296088139',
    projectId: 'morty-pos',
    storageBucket: 'morty-pos.appspot.com',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPIhuE1VohrKfJ2G477J_-zvhhg3BMxQ8',
    appId: '1:965296088139:web:ed5ef50879f8697689d9ce',
    messagingSenderId: '965296088139',
    projectId: 'morty-pos',
    authDomain: 'morty-pos.firebaseapp.com',
    storageBucket: 'morty-pos.appspot.com',
    measurementId: 'G-NPNYMB8NVZ',
  );
}
